# Generated by Django 2.1.1 on 2020-02-02 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200202_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addprop',
            name='image',
        ),
        migrations.AddField(
            model_name='addprop',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='addprop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='addprop',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='addprop',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='addprop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='addprop',
            name='price',
            field=models.IntegerField(),
        ),
    ]
